services:
  postgres:
    image: postgres:16
    container_name: springapi-postgres
    environment:
      POSTGRES_DB: springapi
      POSTGRES_USER: springapi
      POSTGRES_PASSWORD: springapi123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  springapi:
    build: .
    container_name: springapi-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      # Spring profile (optional but recommended)
      SPRING_PROFILES_ACTIVE: docker

      # IMPORTANT: inside Docker, use service name "postgres" not localhost
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/springapi
      SPRING_DATASOURCE_USERNAME: springapi
      SPRING_DATASOURCE_PASSWORD: springapi123

      # Fix compose default syntax: use ':-' not ':'
      APP_JWT_SECRET: "${APP_JWT_SECRET:-4TDFgUheWiyAop6UEMQwXb1u6/6CqxstC6MnA3SEIIw=}"
      APP_JWT_EXPIRATION_MS: "${APP_JWT_EXPIRATION_MS:-3600000}"
    restart: unless-stopped

volumes:
  pgdata:



#services:
#  springapi:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      APP_JWT_SECRET: ${APP_JWT_SECRET:4TDFgUheWiyAop6UEMQwXb1u6/6CqxstC6MnA3SEIIw=}
#      APP_JWT_EXPIRATION_MS: ${APP_JWT_EXPIRATION_MS:3600000}
#    volumes:
#      - h2data:/data
#    restart: unless-stopped
#
#volumes:
#  h2data: