services:
  springapi:
    build: .
    ports:
      - "8080:8080"
    environment:
      APP_JWT_SECRET: ${APP_JWT_SECRET:4TDFgUheWiyAop6UEMQwXb1u6/6CqxstC6MnA3SEIIw=}
      APP_JWT_EXPIRATION_MS: ${APP_JWT_EXPIRATION_MS:3600000}
    volumes:
      - h2data:/data
    restart: unless-stopped

volumes:
  h2data:
